#block ids
ABOUT="about"
SKILLS="skills"
PROJECTS="projects"
EXPERIENCE="experience"
CONTACTS="contacts"
INTRODUCTION="introduction"

#collections
SECTIONS = [ABOUT, SKILLS, PROJECTS, EXPERIENCE, CONTACTS, INTRODUCTION]
CARDS = [SKILLS, PROJECTS, EXPERIENCE, CONTACTS]
ELEMENTS = [ABOUT, INTRODUCTION]